version: 0.2
 
phases:
  pre_build:
    commands:
      - hubUrl=$(aws ssm get-parameters --region us-west-2 --names DAVE_BLACKDUCK_HUB_URL --query Parameters[0].Value)
      - hubUserName=$(aws ssm get-parameters --region us-west-2 --names DAVE_BLACKDUCK_HUB_USERNAME --query Parameters[0].Value)
      - hubPassword=$(aws ssm get-parameters --region us-west-2 --names DAVE_BLACKDUCK_HUB_PASSWORD --with-decryption --query Parameters[0].Value)
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
 
artifacts:
  files:
    - target/ducky-aws-copilot-1.0.war
    - '**/*.pdf'
  discard-paths: yes
