version: 0.2
 
phases:
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
 
artifacts:
  files:
    - target/ducky-aws-copilot-1.0.war
    - '**/*.pdf'
  discard-paths: yes
